create database CK
use CK	

CREATE TABLE NHANVIEN 
(
	MANV CHAR(4) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGSINH SMALLDATETIME,
	DCHI NVARCHAR(50),
	GTINH CHAR(4),
	LUONG MONEY,
	MAPHG CHAR(5)
)
GO
CREATE TABLE PHONGBAN
(
	MAPHG CHAR(5) PRIMARY KEY,
	TENPHG NVARCHAR(50),
	NGTL SMALLDATETIME
)
GO
CREATE TABLE NHANSU
(
	MANV CHAR(4),
	MAPHG CHAR(5),
	CHUCVU CHAR(4),
	NGVL SMALLDATETIME,
	CONSTRAINT PK_NHANSU PRIMARY KEY (MANV,MAPHG)
)
GO
CREATE TABLE DEAN
(
	MADA CHAR(10) PRIMARY KEY,
	MAPHG CHAR(5),
	TENDA NVARCHAR(100),
	NGBD SMALLDATETIME,
	NGKT SMALLDATETIME
)
GO
CREATE TABLE PHANCONG
(
	MANV CHAR(4),
	MADA CHAR(10),
	THOIGIAN SMALLDATETIME,
	CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV,MADA)
)

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_MAPHG_NHANVIEN FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE NHANSU ADD CONSTRAINT FK_MAPHG_NHANSU FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE DEAN ADD CONSTRAINT FK_MAPHG_DEAN FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE PHANCONG ADD CONSTRAINT FK_MADA_PHANCONG FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
ALTER TABLE PHANCONG ADD CONSTRAINT FK_MANV_PHANCONG FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

SELECT NHANVIEN.MANV,HOTEN FROM PHANCONG, NHANVIEN WHERE MADA='DA001' AND NHANVIEN.MANV=PHANCONG.MANV
INTERSECT
SELECT NHANVIEN.MANV,HOTEN FROM PHANCONG, NHANVIEN WHERE MADA='DA003' AND NHANVIEN.MANV=PHANCONG.MANV

SELECT NHANVIEN.MANV,HOTEN,NGSINH FROM NHANVIEN,NHANSU WHERE NHANVIEN.MANV=NHANSU.MANV AND NHANVIEN.MAPHG='003' AND NGVL > '01/01/2010'

SELECT DISTINCT MAPHG FROM NHANSU WHERE MAPHG = (SELECT TOP 1 MANV FROM NHANSU GROUP BY MANV ORDER BY COUNT(MANV) ASC)

SELECT DISTINCT MANV,HOTEN FROM NHANVIEN
WHERE NOT EXISTS 
( SELECT MADA FROM DEAN WHERE COUNT(MADA) > 0
	AND NOT EXISTS (SELECT * FROM PHANCONG WHERE PHANCONG.MANV=NHANVIEN.MANV AND DEAN.MADA=PHANCONG.MADA)
)


CREATE TRIGGER NGVL_INSERT_NHANSU ON NHANSU
FOR INSERT
AS
DECLARE @NGVL SMALLDATETIME, @NGSINH SMALLDATETIME
SELECT @NGVL=NGVL, @NGSINH=NGSINH
FROM NHANVIEN, inserted
WHERE NHANVIEN.MANV=inserted.MANV
IF @NGVL <= @NGSINH
BEGIN
	ROLLBACK TRANSACTION
	PRINT 'INSERT ERROR'
END;

CREATE TRIGGER THOIGIAN_INSERT_DEAN ON PHANCONG
FOR INSERT
AS
DECLARE @THOIGIAN SMALLDATETIME, @NGBD SMALLDATETIME, @NGKT SMALLDATETIME
SELECT @THOIGIAN=THOIGIAN, @NGBD=NGBD, @NGKT=NGKT
FROM DEAN, inserted
WHERE DEAN.MADA=inserted.MADA
IF @THOIGIAN NOT BETWEEN @NGBD AND @NGKT
BEGIN
	ROLLBACK TRANSACTION
	PRINT 'INSERT ERROR'
END;


















